apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/components/infrastructure/networking/tailscale/overlays/stable
  prune: true
  sourceRef:
    kind: GitRepository
    name: staer-robot-fleet
  timeout: 2m
